name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'
      - name: Install modules
        run: |
          cd front
          npm i
      - name: Run tests
        run: |
          cd frontend
          npm run test
